<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AggregatesModels\Baskets\Specifications\**" />
    <Compile Remove="AggregatesModels\Categories\Specifications\**" />
    <Compile Remove="AggregatesModels\Products\Specifications\**" />
    <Compile Remove="AggregatesModels\Products\ValueObjects\**" />
    <EmbeddedResource Remove="AggregatesModels\Baskets\Specifications\**" />
    <EmbeddedResource Remove="AggregatesModels\Categories\Specifications\**" />
    <EmbeddedResource Remove="AggregatesModels\Products\Specifications\**" />
    <EmbeddedResource Remove="AggregatesModels\Products\ValueObjects\**" />
    <None Remove="AggregatesModels\Baskets\Specifications\**" />
    <None Remove="AggregatesModels\Categories\Specifications\**" />
    <None Remove="AggregatesModels\Products\Specifications\**" />
    <None Remove="AggregatesModels\Products\ValueObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
  </ItemGroup>

</Project>
